<a href="https://colab.research.google.com/github/Bora-Ulu/Inflation-Technique/blob/main/Inflation_Technique.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
from numpy import *
from itertools import *
import time
from scipy.sparse import coo_matrix
from scipy.sparse import csr_matrix

def RefiningRows(m): #Takes a matrix as input 
                     #Returns the same matrix with the identical rows removed
    
    M=list(m)
    
    M = ascontiguousarray(M)
    uM = unique(M.view([('', M.dtype)]*M.shape[1]))
    return uM.view(M.dtype).reshape((uM.shape[0], M.shape[1]))

trial_m=array([[1,0,0,1,0],
                 [1,0,1,0,1],
                 [1,0,0,1,0]])
print(trial_m)
print('Refining:')
start = time.time()
print(RefiningRows(trial_m))
print('It takes', time.time()-start, 'seconds to calculate.')
"""

[[1 0 0 1 0]
 [1 0 1 0 1]
 [1 0 0 1 0]]
Refining:
[[1 0 0 1 0]
 [1 0 1 0 1]]
It takes 0.0004589557647705078 seconds to calculate.


In [ ]:
"""
def IntToList(inte, base, leng):#Takes an integer as input
                                #Returns the variable value configuration as a list
    
    List=[int(i) for i in base_repr(inte, base)]
    
    if len(List)<leng:
        
        l=[0 for i in range(leng-len(List))]
        l.extend(List)
        List=l
        
    return List
print('The integer 1456 in the form of a list:')
start = time.time()
print(IntToList(1456, 4, 12))
print('It takes', time.time()-start, 'seconds to calculate.')
"""

The integer 1456 in the form of a list:
[0, 0, 0, 0, 0, 0, 1, 1, 2, 3, 0, 0]
It takes 0.0001227855682373047 seconds to calculate.


In [ ]:
"""
def ListToInt(List, Base):#Takes a varaible value configuration as a list
                          #Returns the corresponding integer
    
    L=list(List)
    r = str("".join([str(i) for i in L]))
    inte = int(r, base = Base)
    
    return inte
a=IntToList(1456, 4, 12)
print('We have a list:')
print(a)
print('This list corresponds to the integer:')
start = time.time()
print(ListToInt(a, 4))
print('It takes', time.time()-start, 'seconds to calculate.')
"""

We have a list:
[0, 0, 0, 0, 0, 0, 1, 1, 2, 3, 0, 0]
This list corresponds to the integer:
1456
It takes 9.012222290039062e-05 seconds to calculate.


In [ ]:
"""
def IntToArray32(inte,cnt):
    
    a=array([inte],dtype=uint32)
    a=a.view(uint8)
    a=unpackbits(a,count=cnt)
    
    return a

def ArrayToInt32(ar):

    A=ar
    A=concatenate((A, array([0,0,0,0,0,0,0,0])), axis=0)
    A=A.reshape(-1,4, 8)
    A=packbits(A).view(uint32)
    
    return A

def IntToListBin(inte,leng):
    
    List=format(inte, 'b')
    List=[i for i in List]
    
    if len(List)<leng:
        
        l=[0 for i in range(leng-len(List))]
        l.extend(List)
        List=l    
    
    return List
t=100000
inte=12345
base=4
start = time.time()
for i in range(t):
  A=IntToArray32(inte,-8)
  B=ArrayToInt32(A)
print('It took', time.time()-start, 'seconds with bit conversion.')

start = time.time()
for i in range(t):
  A=IntToList(inte,base,12)
  B=ListToInt(A,base)
print('It took', time.time()-start, 'seconds with base conversion.')

start = time.time()
for i in range(t):
    A=IntToListBin(inte, 24)
    B=ListToInt(A,2)
print('It took', time.time()-start, 'seconds with bin.')
"""

It took 0.842592716217041 seconds with bit conversion.
It took 0.6444659233093262 seconds with base conversion.
It took 0.6410398483276367 seconds with bin.


In [ ]:
"""
def Symmetry_Op(operation, inte):#Takes the exchange operation of copy latent variables and the values of the observable variables as integers
                                   #Returns the corresponding observable values for the resultant identical probability in the form of an integer
    
    # The input list is of the form: [A1,A2,A3,A4,B1,B2,B3,B4,C1,C2,C3,C4]
    
    
    
    array=IntToList(inte, 4 ,12)
    
    if operation == 'X1_X2': #Exchanging \Lambda_{1}^{AB} and \Lambda_{2}^{AB}
        
        array[0],array[1],array[2],array[3],array[4],array[6]array[5],array[7]=array[1],array[0],array[3],array[2],array[6],array[4],array[7],array[5] 
        #A1 -- A2, #A3 -- A4, #B1 -- B3,= #B2 -- B4
        
        a=ListToInt(array , 4)
    
        return a
        
    elif operation == 'Y1_Y2': #Exchanging \Lambda_{1}^{AC} and \Lambda_{2}^{AC}
        
        array[0],array[2]=array[2],array[0] #A1 -- A3
        array[1],array[3]=array[3],array[1] #A2 -- A4
        array[8],array[9]=array[9],array[8] #C1 -- C2
        array[10],array[11]=array[11],array[10] #C3 -- C4
        
        a=ListToInt(array , 4)
        
        return a
        
    elif operation == 'Z1_Z2': #Exchanging \Lambda_{1}^{BC} and \Lambda_{2}^{BC}

        array[4],array[5]=array[5],array[4] #B1 -- B2
        array[6],array[7]=array[7],array[6] #B3 -- B4
        array[8],array[10]=array[10],array[8] #C1 -- C3
        array[9],array[11]=array[11],array[9] #C2 -- C1
        
        a=ListToInt(array , 4)
        
        return a
    
    else:
        print('Error: Enter a valid operation.')

Op='X1_X2'
inte=634567
print('Integer before the exchange:')
print(inte)
print('List before the exchange:')
print(IntToList(inte, 4, 12))
print('Integer after the exchange:')
start = time.time()
print(Symmetry_Op(Op, inte))
print('It takes', time.time()-start, 'seconds to calculate.')
print('List after the exchange:')
print(IntToList(Symmetry_Op(Op, inte) , 4, 12))
"""

Integer before the exchange:
634567
List before the exchange:
[0, 0, 2, 1, 2, 2, 3, 2, 3, 0, 1, 3]
Integer after the exchange:
453319
It takes 9.298324584960938e-05 seconds to calculate.
List after the exchange:
[0, 0, 1, 2, 3, 2, 2, 2, 3, 0, 1, 3]


In [ ]:
"""
def Symmetric_Arrays(Op_list, inte):#Takes a list of latent variable copy index exchange operations and the values of the observable variables as input as integer
                                     #Returns all configurations of observable variable values that have identical probabilities in the form of a list of integers
    A=[inte]
    
    permutation1=list(permutations(Op_list, 1))# A single copy index exchange operation on latent variables (X1_X2, Y1_Y2 and Z1_Z2)
    permutation2=list(permutations(Op_list, 2))# Two copy index exchange operations on latent variables
    permutation3=list(permutations(Op_list, 3))# Three copy index exchange operations on latent variables
    
    for i in range(len(permutation1)):#Lists the configurations of observable variable values that have identical probabilities for a single exchange
        
        A.append(Symmetry_Op(permutation1[i][0],inte))
    
    for i in range(len(permutation2)):#Lists the configurations of observable variable values that have identical probabilities for a two exchange operations
        
        inte1=Symmetry_Op(permutation2[i][0],inte)
        A.append(Symmetry_Op(permutation2[i][1],inte1))
        
    for i in range(len(permutation3)):#Lists the configurations of observable variable values that have identical probabilities for a three exchange operations

        inte1=Symmetry_Op(permutation3[i][0],inte)
        inte2=Symmetry_Op(permutation3[i][1],inte1)
        A.append(Symmetry_Op(permutation3[i][2],inte2))
    
    #A=list(set(A))#Removes identical configurations from the list
    
    return A

Op_list=['X1_X2','Y1_Y2','Z1_Z2']
inte=634567
print('Configuration of the variable values in the form of an integer:')
print(inte)
print('All configurations that have the same probabilities as this configuration, in the form of integers:')
start = time.time()
print(Symmetric_Arrays(Op_list, inte))
print('It takes', time.time()-start, 'seconds to calculate.')
"""

Configuration of the variable values in the form of an integer:
634567
All configurations that have the same probabilities as this configuration, in the form of integers:
[440956, 437884, 9481789, 453319, 634567, 9481171, 6339283, 6336211, 633724, 6351421]
It takes 0.00040078163146972656 seconds to calculate.


In [ ]:
"""
def RowOfaColumn(inte):#Takes a column configuration as an integer
                       #Finds the two symmetric rows that have a "1" in the corresponding column of the description matrix
                       #Returns the row with the smaller index
    
    c=IntToList(inte, 4 , 12)
    cc=[c[3],c[0],c[7],c[4],c[11],c[8]]
    c=[c[0],c[3],c[4],c[7],c[8],c[11]]
    c=ListToInt(c,4)
    cc=ListToInt(cc,4)
    if cc >= c:
        return c
    else:
        return cc

co=634567
print('For the column represented by the integer:')
print(co)
print('The row at which this column has its only 1 value is:')
start = time.time()
print(RowOfaColumn(co))
print('It takes', time.time()-start, 'seconds to calculate.')
"""

For the column represented by the integer:
634567
The row at which this column has its only 1 value is:
431
It takes 0.00011396408081054688 seconds to calculate.


In [ ]:
"""
def RowSymmetry(inte):#Takes a row as input
                      #Returns the symmetric row
    
    c=IntToList(inte,4,6)
    c=[c[1],c[0],c[3],c[2],c[5],c[4]]
    c=ListToInt(c,4)
    
    return c
def RowList(inte):#Creates the row list (Rows) by removing the symmetrical rows
                  #Returns the configuration of a row specified by the input integer
    
    Checklist=[0 for i in range(4**6)]
    
    i=0
    v=0
    Rows=[0]
    while i in range(len(Checklist)-1):
        
        if Checklist[i+1] == 0:
            
            R=RowSymmetry(i+1)
            Rows.append(i+1)
            Checklist[R]=1
            
        i=i+1
    
    Row=IntToList(Rows[inte],4,6)
    
    return Row,Rows
h=2000
start = time.time()
Row,Rows=RowList(h)
print('It takes', time.time()-start, 'seconds to calculate.')
print('We have the configuration for the',h,'th row as:')
print('{A1,A4,B1,B4,C1,C4}')
print(Row)
print('And the total number of rows after symmetrization is:')
print(len(Rows))
"""

It takes 0.013324975967407227 seconds to calculate.
We have the configuration for the 2000 th row as:
{A1,A4,B1,B4,C1,C4}
[3, 3, 0, 3, 3, 2]
And the total number of rows after symmetrization is:
2080


In [ ]:
"""
def remove_zero_rows(M):#Removes the zero rows of a sparse matrix
  M = csr_matrix(M)
  num_nonzeros = diff(M.indptr)
  return M[num_nonzeros != 0]

def MDM():#Returns the description matrix
    
    Op_list=['X1_X2','Y1_Y2','Z1_Z2']
    
    Checklist=[0 for i in range(4**12)]#Creates the checklist
    
    j=0#specifies the variable value configurations for columns
    v=0#specifies the idecies of the columns
    while j in range(len(Checklist)):
        
        if Checklist[j] == 0:#Runs for the "0" valued elements of the checklist
            
            S=Symmetric_Arrays(Op_list, j)#Finds the symmetric columns of a colum specified by an integer
            
            if j == 0:#Initial iteration
        
                Columns=[v for k in range(len(S))]
                v=v+1
                Rows=[RowOfaColumn(k) for k in S]
                
            else:#Extends the row and column arrays that will form the coo sparse matrix
                
                Columns.extend((v for k in range(len(S))))#Extends the column indecies linearly
                v=v+1
                Rows.extend((RowOfaColumn(k) for k in S))#Extends the row indecies with the rows corresponding the the symmetric columns
                
            for x in S:#Modifies the checklist
                Checklist[x]=1
            
        j=j+1
        
    data=[1 for i in range(len(Rows))]#creates the data list for the sparse matrix
    m = coo_matrix((array(data), (array(Rows), array(Columns))))#creates the sparse matrix
    M=remove_zero_rows(m)#removes the zero rows arising from the symmetric rows
    M = M.toarray()
    return M

start = time.time()
M=MDM()
print('It takes', time.time()-start, 'seconds to calculate the marginal description matrix.')
print('It has',len(M),'rows and',len(M[0]),'columns')
print('Its explicit form is:')
print(M)
"""

It takes 767.6190559864044 seconds to calculate the marginal description matrix.
It has 2080 rows and 2123776 columns
Its explicit form is:
[[1 2 2 ... 0 0 0]
 [0 2 0 ... 0 0 0]
 [0 0 2 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 2 0]
 [0 0 0 ... 1 2 1]]


In [1]:
from numpy import *
from itertools import *
import time
from scipy.sparse import coo_matrix
from scipy.sparse import csc_matrix
from scipy.sparse import csr_matrix
from cvxopt import matrix, solvers, sparse, spmatrix

def IntToList(inte, base, leng):
    
    List=[int(i) for i in base_repr(inte, base)]
    
    if len(List)<leng:
        
        l=[0 for i in range(leng-len(List))]
        l.extend(List)
        List=l
        
    return List
        
def ListToInt(List, Base):
    
    L=list(List)
    r = str("".join([str(i) for i in L]))
    inte = int(r, base = Base)
    
    return inte


def IntToArray32(ar):# Takes a huge column vector as input
                     # Returns a matrix where the rows are the base-4 binary expansions of each element of the input array
    
    a=ar
    a=a.astype('uint32')
    a=a.view(uint8)
    a=unpackbits(a,count=-8,axis=1)
    
    return a

def ArrayToInt32(matrix):#Takes the output matrix of IntToArray32() as input
                         #Returns the column vector with each row of the input turned into an integer 

    A=matrix
    A=concatenate((A, zeros((len(A),8),dtype=uint32)), axis=1)
    A=A.reshape(-1,4, 8)
    A=packbits(A).view(uint32)
    A=array([A]).T
    
    return A

def ArrayToInt16(matrix):#Does the same as ArrayToInt16() however, this time the input has 12 binary digits that represent a 6 digit base-4 integer
    
    A=matrix
    A=concatenate((A, zeros((len(A),4),dtype=uint16)), axis=1)
    A=A.reshape(-1,2, 8)
    A=packbits(A,bitorder='little').view(uint16)
    #A=array([A]).T
    
    return A

ar=array([arange(4**12)]).T
start = time.time()
A=IntToArray32(ar)
print('It took', time.time()-start, 'seconds.')
print(A[2])
start = time.time()
A=ArrayToInt32(A)
print('It took', time.time()-start, 'seconds.')
print(A[2])

It took 0.2918868064880371 seconds.
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
It took 3.81207275390625 seconds.
[2]


In [2]:
def Symmetry_Op(operation, ar):#Takes the exchange opration of copy latent variables and the values of the observable variables as input 
                                   #Returns the corresponding observable values for the resultant identical probability
    
    # The input list is of the form: [A1,A2,A3,A4,B1,B2,B3,B4,C1,C2,C3,C4]
    
    
    
    A=IntToArray32(ar)
    
    if operation == 'X1_X2': #Exchanging \Lambda_{1}^{AB} and \Lambda_{2}^{AB}
        
        A[:,[0,1,2,3]] = A[:,[2,3,0,1]] #A1 -- A2
        A[:,[4,5,6,7]] = A[:,[6,7,4,5]] #A3 -- A4
        A[:,[8,9,12,13]] = A[:,[12,13,8,9]] #B1 -- B3
        A[:,[10,11,14,15]] = A[:,[14,15,10,11]] #B2 -- B4
        
        A=ArrayToInt32(A)
    
        return A
        
    elif operation == 'Y1_Y2': #Exchanging \Lambda_{1}^{AC} and \Lambda_{2}^{AC}
        
        A[:,[0,1,4,5]] = A[:,[4,5,0,1]] #A1 -- A3
        A[:,[2,3,6,7]] = A[:,[6,7,2,3]] #A2 -- A4
        A[:,[16,17,18,19]] = A[:,[18,19,16,17]] #C1 -- C2
        A[:,[20,21,22,23]] = A[:,[22,23,20,21]] #C3 -- C4
        
        A=ArrayToInt32(A)
        
        return A
        
    elif operation == 'Z1_Z2': #Exchanging \Lambda_{1}^{BC} and \Lambda_{2}^{BC}
        
        A[:,[8,9,10,11]] = A[:,[10,11,8,9]] #B1 -- B2
        A[:,[12,13,14,15]] = A[:,[14,15,12,13]] #B3 -- B4
        A[:,[16,17,20,21]] = A[:,[20,21,16,17]]#C1 -- C3
        A[:,[18,19,22,23]] = A[:,[22,23,18,19]] #C2 -- C1
        
        A=ArrayToInt32(A)
        
        return A
    
    else:
        print('Error: Enter a valid operation.')
start = time.time()
A=Symmetry_Op('X1_X2',ar)
print('It took', time.time()-start, 'seconds.')

It took 4.893877983093262 seconds.


In [3]:
def Symmetric_Arrays(Op_list, ar):#Takes a list of laten variable copy index exchange operations and the values of the observable variables as input as input 
                                     #Returns all configurations of observable variable values that have identical probabilities in the form of a list
    A=ar
    
    permutation1=list(permutations(Op_list, 1))# A single copy index exchange operation on latent variables (X1_X2, Y1_Y2 and Z1_Z2)
    permutation3=list(permutations(Op_list, 3))# Three copy index exchange operations on latent variables
    
    for i in range(len(permutation1)):#Lists the configurations of observable variable values that have identical probabilities for a single exchange
        
        A=hstack((A,Symmetry_Op(permutation1[i][0],ar)))
        
    for i in range(len(permutation3)):#Lists the configurations of observable variable values that have identical probabilities for a three exchange operations

        ar1=Symmetry_Op(permutation3[i][0],ar)
        A=hstack((A,Symmetry_Op(permutation3[i][1],ar1)))
        ar2=Symmetry_Op(permutation3[i][1],ar1)
        A=hstack((A,Symmetry_Op(permutation3[i][2],ar2)))
    
    #A=array([unique(A)]).T#Removes identical configurations from the list
        
    return A
Op_list=['X1_X2','Y1_Y2','Z1_Z2']
start = time.time()
A=Symmetric_Arrays(Op_list, ar)
print('It took', time.time()-start, 'seconds.')

It took 142.61117219924927 seconds.


In [4]:
def CorRowsNoSymmetry(ar):
    
    A=IntToArray32(ar)
    
    #A=A[:,[0,1,6,7,8,9,14,15,16,17,22,23]]
    A=A[:,[23,22,17,16,15,14,9,8,7,6,1,0]]

    A=ArrayToInt16(A)
    
    return A

def CorRows(ar):#Creates an array with all the rows that have a "1" in the corresponding column of the input array. the row symmetries are applied
                #by choosing the row with the smaller index among the symmetric rows
    
    A=IntToArray32(ar)
    
    A1=A[:,[0,1,6,7,8,9,14,15,16,17,22,23]]
    #A1=A[:,[14,9,8,7,6,1,0,23,22,17,16,15]]
    
    A1=ArrayToInt16(A1)
    
    A=A[:,[23,22,17,16,15,14,9,8,7,6,1,0]]
    
    A=ArrayToInt16(A)
    A=vstack((A,A1))
    A=amin(A,axis=0)
    
    return A
start = time.time()
A=CorRows(ar)
print('It took', time.time()-start, 'seconds.')

It took 3.7859010696411133 seconds.


In [5]:
def NewCols(ar):#Applies the symmetry condition to the columns by choosing the column with the smaller index among the symmetric columns
    
    Op_list=['X1_X2','Y1_Y2','Z1_Z2']
    
    A=Symmetric_Arrays(Op_list, ar)
    
    A=amin(A,axis=1)
    
    #A=A[:,0]
    
    return A
start = time.time()
A=NewCols(ar)
print('It took', time.time()-start, 'seconds.')

It took 143.67358303070068 seconds.


In [6]:
def remove_zero_rows(M):# Removes zero rows from sparse array
  M = csr_matrix(M)
  num_nonzeros = diff(M.indptr)
  return M[num_nonzeros != 0]

def drop_zero_columns(m):#removes zero columns from sparse array
    
    nz_cols, new_col = unique(m.col, return_inverse=True)
    m.col[:] = new_col
    m._shape = (m.shape[0], len(nz_cols))

    return m

def MDM():#Creates the MDM by combining the outputs of the previous functions in a coo sparse array
        
    ar=array([arange(4**12)]).T
        
    Rows=CorRows(ar)
    Columns=NewCols(ar)
        
    data=[1 for i in range(len(Rows))]
    
    m = coo_matrix((data, (Rows, Columns)),dtype=uint8)
    M=drop_zero_columns(m)
    M=remove_zero_rows(M)
    M = M.toarray()
    
    return M
start = time.time()
M=MDM()
print('It took', time.time()-start, 'seconds.')
print('The number of columns in the MDM:')
print(len(M[0]))
print('The number of rows in the MDM:')
print(len(M))

It took 154.16555166244507 seconds.
The number of columns in the MDM:
2123776
The number of rows in the MDM:
2080


In [8]:
def RowSymmetry(inte):#Takes a row as input
                      #Returns the symmetric row
    
    c=IntToList(inte,4,6)
    c=[c[1],c[0],c[3],c[2],c[5],c[4]]
    c=ListToInt(c,4)
    
    return c


def b(Data):#Creates the b vector by removing the symmetrical rows and using the input data with the correct multiplications of the probabilities.
    
    Checklist=[0 for i in range(4**6)]
    i=0
    b=[]
    while i in range(len(Checklist)):
        
        if Checklist[i] == 0:
            
            R=RowSymmetry(i)
            
            c=IntToList(i,4,6)
            c1=[c[0],c[1],c[2]]
            c1=ListToInt(c1,4)
            c2=[c[3],c[4],c[5]]
            c2=ListToInt(c2,4)
            
            c3=Data[c1]*Data[c2]
            
            b.append(c3)
            Checklist[R]=1
            
        i=i+1
    
    b=array([b]).T
    
    return b
Data=[0.12199995751046305, 0.0022969343799089472, 0.001748319476328954, 3.999015242496535e-05, 0.028907881434196828, 0.0005736087488455967, 0.0003924033706699725, 1.1247230369521505e-05, 0.0030142577390317635, 0.09234476010282468, 4.373922921480586e-05, 0.0014533921021948346, 0.0007798079722868244, 0.024091567451515063, 1.1247230369521505e-05, 0.0003849052170902915, 0.020774884184769502, 0.000396152447459813, 0.0003049249122403608, 4.998769053120669e-06, 0.10820335492385, 0.0020794879260981982, 0.0015546171755205281, 2.4993845265603346e-05, 0.0006260958239033638, 0.020273757587194154, 7.498153579681003e-06, 0.0003374169110856452, 0.0028942872817568676, 0.08976414557915113, 2.624353752888351e-05, 0.0012984302615480939, 0.002370666223442477, 4.7488306004646356e-05, 0.0999928767540993, 0.001957018084296742, 0.0006198473625869629, 8.747845842961171e-06, 0.02636975644747481, 0.0005198719815245496, 1.4996307159362007e-05, 0.000403650601039494, 0.0005498645958432735, 0.017359475229224805, 7.123245900696953e-05, 0.002346922070440154, 0.0033754188031197316, 0.10295964618712641, 0.00038740460161685187, 7.498153579681003e-06, 0.01608353942841575, 0.000306174604503641, 0.0021319750011559654, 4.248953695152569e-05, 0.09107007399427891, 0.001860791780024169, 5.998522863744803e-05, 0.0018395470115484063, 0.002570616985567304, 0.0766411271224461, 1.874538394920251e-05, 0.00048238121362614454, 0.0006410921310627258, 0.020223769896662948]
start = time.time()
b=b(Data)
print('It took', time.time()-start, 'seconds.')
print('The length of the vector b is:')
print(len(b))

It took 0.02775096893310547 seconds.
The lenght of the vector b is:
2080


In [9]:
def scipy_sparse_to_spmatrix(A):#Turns a scipy sparse array into a cvxopt sparse array
    coo = A.tocoo()
    SP = spmatrix(coo.data.tolist(), coo.row.tolist(), coo.col.tolist(), size=A.shape, tc='d')
    return SP

A=M
c=b
z=zeros((len(A[0]),1))#Creates the right side of the inequality y.M>=0 in the form of a vector
    
A=A.astype(double)#Changes the format of the input arrays in a way that cvxopt functions will accept
c=c.astype(double)
z=z.astype(double)
A=transpose(A)#Changes the rows with columns as this is how cvxopt accepts the input matrix M
A=coo_matrix(A)#Changes the input matrix M to sparse form so that the solver won't crash the python kernel

"""
A=matrix(A)
c=matrix(c)
z=matrix(z)
"""

A=scipy_sparse_to_spmatrix(A)#Turns the scipy sparse array M into cvxopt sparse array
c=matrix(c)#Turns numpy array objective function to cvxopt dense array
z=matrix(z)

sol=solvers.lp(c,A,z, solver='mosek')#Solves the linear program

Problem
  Name                   :                 
  Objective sense        : min             
  Type                   : LO (linear optimization problem)
  Constraints            : 2123776         
  Cones                  : 0               
  Scalar variables       : 2080            
  Matrix variables       : 0               
  Integer variables      : 0               

Optimizer started.
Presolve started.
Eliminator - tries                  : 0                 time                   : 0.00            
Lin. dep.  - tries                  : 0                 time                   : 0.00            
Lin. dep.  - number                 : 0               
Presolve terminated. Time: 0.87    
Optimizer terminated. Time: 1.13    


Interior-point solution summary
  Problem status  : DUAL_INFEASIBLE
  Solution status : DUAL_INFEASIBLE_CER
  Primal.  obj: -4.0900086883e-04   nrm: 2e+00    Viol.  con: 0e+00    var: 0e+00  

Basic solution summary
  Problem status  : DUAL_INFEASIBLE
  Soluti