<a href="https://colab.research.google.com/github/Bora-Ulu/Inflation-Technique/blob/main/Inflation_Technique.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from numpy import *
from itertools import *
import time

def RefiningRows(m): #Takes a matrix as input 
                     #Returns the same matrix with the identical rows removed
    
    M=list(m)
    
    M = ascontiguousarray(M)
    uM = unique(M.view([('', M.dtype)]*M.shape[1]))
    return uM.view(M.dtype).reshape((uM.shape[0], M.shape[1]))

trial_m=array([[1,0,0,1,0],
                 [1,0,1,0,1],
                 [1,0,0,1,0]])
print(trial_m)
print('Refining:')
start = time.time()
print(RefiningRows(trial_m))
print('It takes', time.time()-start, 'seconds to calculate.')

[[1 0 0 1 0]
 [1 0 1 0 1]
 [1 0 0 1 0]]
Refining:
[[1 0 0 1 0]
 [1 0 1 0 1]]
It takes 0.0005285739898681641 seconds to calculate.


In [2]:
def Symmetry_Op(operation, array0):#Takes the exchange opration of copy latent variables and the values of the observable variables as input 
                                   #Returns the corresponding observable values for the resultant identical probability 
    
    # The input list is of the form: [A1,A2,A3,A4,B1,B2,B3,B4,C1,C2,C3,C4]
    
    
    
    array=list(array0)
    
    if operation == 'X1_X2': #Exchanging \Lambda_{1}^{AB} and \Lambda_{2}^{AB}
        
        array[0],array[1]=array[1],array[0] #A1 -- A2
        array[2],array[3]=array[3],array[2] #A3 -- A4
        array[4],array[6]=array[6],array[4] #B1 -- B3
        array[6],array[7]=array[7],array[6] #B3 -- B4
    
        return array
        
    elif operation == 'Y1_Y2': #Exchanging \Lambda_{1}^{AC} and \Lambda_{2}^{AC}
        
        array[0],array[2]=array[2],array[0] #A1 -- A3
        array[1],array[3]=array[3],array[1] #A2 -- A4
        array[8],array[9]=array[9],array[8] #C1 -- C2
        array[10],array[11]=array[11],array[10] #C3 -- C4
        
        return array
        
    elif operation == 'Z1_Z2': #Exchanging \Lambda_{1}^{BC} and \Lambda_{2}^{BC}

        array[4],array[5]=array[5],array[4] #B1 -- B2
        array[6],array[7]=array[7],array[6] #B3 -- B4
        array[8],array[10]=array[10],array[8] #C1 -- C3
        array[9],array[11]=array[11],array[9] #C2 -- C1
        
        return array
    
    else:
        print('Error: Enter a valid operation.')

Op='X1_X2'
ar=[1,0,0,1,1,1,0,1,1,0,1,0]
print('Before the exchange:')
print(ar)
print('After the exchange:')
start = time.time()
print(Symmetry_Op(Op, ar))
print('It takes', time.time()-start, 'seconds to calculate.')

Before the exchange:
[1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0]
After the exchange:
[0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0]
It takes 8.654594421386719e-05 seconds to calculate.


In [3]:
def Symmetric_Arrays(Op_list, array):#Takes a list of laten variable copy index exchange operations and the values of the observable variables as input as input 
                                     #Returns all configurations of observable variable values that have identical probabilities in the form of a list
    A=list(array)
    
    permutation1=list(permutations(Op_list, 1))# A single copy index exchange operation on latent variables (X1_X2, Y1_Y2 and Z1_Z2)
    permutation2=list(permutations(Op_list, 2))# Two copy index exchange operations on latent variables
    permutation3=list(permutations(Op_list, 3))# Three copy index exchange operations on latent variables
    
    for i in range(len(permutation1)):#Lists the configurations of observable variable values that have identical probabilities for a single exchange
        
        A=vstack((A,Symmetry_Op(permutation1[i][0],list(array))))
    
    for i in range(len(permutation2)):#Lists the configurations of observable variable values that have identical probabilities for a two exchange operations
        
        array1=Symmetry_Op(permutation2[i][0],list(array))
        A=vstack((A,Symmetry_Op(permutation2[i][1],list(array1))))
        
    for i in range(len(permutation3)):#Lists the configurations of observable variable values that have identical probabilities for a three exchange operations

        array1=Symmetry_Op(permutation3[i][0],list(array))
        array2=Symmetry_Op(permutation3[i][1],list(array1))
        A=vstack((A,Symmetry_Op(permutation3[i][2],list(array2))))
    
    A=RefiningRows(A)#Removes identical configurations from the list
    
    return A

Op_list=['X1_X2','Y1_Y2','Z1_Z2']
print('Configuration of the variable values:')
print(ar)
print('All other configurations that have the same probabilities:')
start = time.time()
print(Symmetric_Arrays(Op_list, ar))
print('It takes', time.time()-start, 'seconds to calculate.')

Configuration of the variable values:
[1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0]
All other configurations that have the same probabilities:
[[0 1 1 0 0 1 1 1 1 0 1 0]
 [0 1 1 0 1 0 1 1 1 0 1 0]
 [0 1 1 0 1 1 0 1 0 1 0 1]
 [0 1 1 0 1 1 0 1 1 0 1 0]
 [0 1 1 0 1 1 1 0 0 1 0 1]
 [1 0 0 1 0 1 1 1 0 1 0 1]
 [1 0 0 1 1 0 1 1 0 1 0 1]
 [1 0 0 1 1 1 0 1 0 1 0 1]
 [1 0 0 1 1 1 0 1 1 0 1 0]
 [1 0 0 1 1 1 1 0 1 0 1 0]]
It takes 0.0016353130340576172 seconds to calculate.


In [4]:
def RowList():#Returns the list representing each row of the matrix by assigning configurations of observable variable values for the ai-expressable set {A2,B2,C2} 

    Row_List_Row=list(product(range(2), repeat=3))#RowList however all elements of the list are in a row
    for i in range(len(Row_List_Row)):#Orders elements of RowList in a column to make it easier to read
        
        if i == 0:
           Row_List_Column=Row_List_Row[i]
        else:  
           Row_List_Column=vstack((Row_List_Column,Row_List_Row[i]))
        
    return Row_List_Column
print('{A2,B2,C2}')
start = time.time()
print(RowList())
print('It takes', time.time()-start, 'seconds to calculate.')

{A2,B2,C2}
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
It takes 0.0005424022674560547 seconds to calculate.


In [5]:
def Columns_in_M(colum):#Takes a configuration of observable variable values as input
                        #Returns the corresponding column of the marginal description matrix
    R=list(RowList())#Takes the representation of the rows
    C=[0 for i in range(len(R))]#Creates an empty array to fill and create the column
    
    for i in range(len(R)):#Matches the values of the observable variables with the values of A2,B2,C2 corresponding to the marginal. If the values match fills that spot with 1 if values don't match, fills the spot with 0
        if (colum[1] == R[i][0])&(colum[5] == R[i][1])&(colum[9] == R[i][2]):
            C[i]=1
    c=array([C]).T
    return c
print('Configuration of the variable values:')
print(ar)
print('Corresponding column of M:')
start = time.time()
print(Columns_in_M(ar))
print('It takes', time.time()-start, 'seconds to calculate.')

Configuration of the variable values:
[1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0]
Corresponding column of M:
[[0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]]
It takes 0.0006835460662841797 seconds to calculate.


In [6]:
def Matrix():#Creates the marginal description matrix
    
     Op_list=['X1_X2','Y1_Y2','Z1_Z2']
     All_P=list(product(range(2), repeat=12))#Creates a list of all possible configurations for the observable variable values
     i=0#To iterate the while loop
     while i in range(len(All_P)):
         
         if i == 0:#for the initial iteration
             
             S=Symmetric_Arrays(Op_list, All_P[i])#Takes a configuration and finds the list of configurations with identical probabilities
             m=Columns_in_M(S[0])#Computes the column of the description matrix that corresponds to the first configuration of the list
             for x in range(len(S)-1):#iterates over the elements of the list of configurations with identical probabilities
                 m=m+Columns_in_M(S[x+1])#sums the columns that correspond to identical probabilities
                 index=where(all(array(All_P)==array(S[x+1]),axis=1))#Finds the index of the observable variable value configurations that just had thier columns in the description matrix summed, inside the list of all possible configurations for the observable variable values
                 All_P.pop(int(index[0]))#Removes the observable variable value configurations that just had thier columns in the description matrix summed, from the list of all possible configurations for the observable variable values
             M=m#creates the first column of the description matrix
         else:
             
             S=Symmetric_Arrays(Op_list, All_P[i])#Does the same as in the if statement above
             m=Columns_in_M(S[0])
             for x in range(len(S)-1):
                 m=m+Columns_in_M(S[x+1])
                 index=where(all(array(All_P)==array(S[x+1]),axis=1))
                 if index[0].size > 0:#Checks whether the observable variable value configurations that just had thier columns in the description matrix summed, have already been removed from the list of all possible configurations for the observable variable values
                     All_P.pop(int(index[0][0]))
             #M=concatenate((M,m),axis=1)
             M=hstack((M,m))#Concatenates the columns of the description matrix to form the description matrix 
         i=i+1
     return M

print('The row list:')
print(RowList())
print('The marginal description matrix:')
start = time.time()
print(Matrix())
print('It takes', time.time()-start, 'seconds to calculate.')

The row list:
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
The marginal description matrix:
[[1 3 1 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 1 3 1]]
It takes 12.830290794372559 seconds to calculate.
